[svn] Retrieving modifications about naming of system variable from trunk.
Exception: Log::do_log() uses "%m" format string instead of $ERRNO parameter.